### PR TITLE
[FIX] adapters/Memory: Return cloned resources

### PR DESCRIPTION
**Pull request by matz3**
**Thank you for your contribution!** 🙌

To get it merged faster, kindly review the checklist below:

## Pull Request Checklist
- [ ] Reviewed the [Contributing Guidelines](https://github.com/SAP/ui5-tooling/blob/master/CONTRIBUTING.md#-contributing-code)
    + Especially the [How to Contribute](https://github.com/SAP/ui5-tooling/blob/master/CONTRIBUTING.md#how-to-contribute) section 
- [ ] [No merge commits](https://github.com/SAP/ui5-tooling/blob/master/docs/Guidelines.md#no-merge-commits)
- [ ] [Correct commit message style](https://github.com/SAP/ui5-tooling/blob/master/docs/Guidelines.md#commit-message-style)

### CODE REVIEW

**Comment by RandomByte** [comment]
Missing tests

**Comment by matz3** [comment]
True. I've just made sure that existing tests do not break, but we should also have new tests. I'll take care of it.

**Comment by matz3** [comment]
Rebased + added tests

**Comment by RandomByte** [comment]
As discussed today, we should also clone on write in order to have a similar behavior as with the FS Adapter where for example a resources content can't be changed after it has been written.

On read however, we can use the createStream parameter to skip copying a resources content.

**Pull request merged**
